image: elixir:1.11-alpine

stages:
  - lint
  - test

variables:
  MIX_ENV: "test"

cache:
  key:
    files:
      - mix.lock
  paths:
    - deps

lint:
  before_script:
    - mix local.rebar --force
    - mix local.hex --force
    - mix deps.get --only test
  script: mix format --check-formatted

test:
  before_script:
    - mix local.rebar --force
    - mix local.hex --force
    - mix deps.get --only test
  script: mix test
